//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HanditinModel", "FK_Student_Class", "Class", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MVCtest.Models.Class), "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCtest.Models.Student), true)]
[assembly: EdmRelationshipAttribute("HanditinModel", "FK_group_leader_sid", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MVCtest.Models.Student), "Group", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCtest.Models.Group), true)]
[assembly: EdmRelationshipAttribute("HanditinModel", "FK_group_student", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MVCtest.Models.Student), "Group", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCtest.Models.Group), true)]
[assembly: EdmRelationshipAttribute("HanditinModel", "FK_submission_group", "Group", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MVCtest.Models.Group), "Submission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCtest.Models.Submission), true)]
[assembly: EdmRelationshipAttribute("HanditinModel", "FK_project_teacher", "Teacher", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MVCtest.Models.Teacher), "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCtest.Models.Project), true)]
[assembly: EdmRelationshipAttribute("HanditinModel", "FK_submission_project", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MVCtest.Models.Project), "Submission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCtest.Models.Submission), true)]
[assembly: EdmRelationshipAttribute("HanditinModel", "FK_socre_submission", "Submission", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MVCtest.Models.Submission), "Score", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCtest.Models.Score), true)]
[assembly: EdmRelationshipAttribute("HanditinModel", "FK_socre_teacher", "Teacher", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MVCtest.Models.Teacher), "Score", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCtest.Models.Score), true)]
[assembly: EdmRelationshipAttribute("HanditinModel", "FK_student_user", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MVCtest.Models.User), "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MVCtest.Models.Student), true)]
[assembly: EdmRelationshipAttribute("HanditinModel", "FK_teacher_user", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MVCtest.Models.User), "Teacher", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MVCtest.Models.Teacher), true)]
[assembly: EdmRelationshipAttribute("HanditinModel", "Enrol", "Group", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCtest.Models.Group), "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCtest.Models.Student))]
[assembly: EdmRelationshipAttribute("HanditinModel", "SubmittedWork", "Submission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCtest.Models.Submission), "Work", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVCtest.Models.Work))]

#endregion

namespace MVCtest.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HanditinEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HanditinEntities object using the connection string found in the 'HanditinEntities' section of the application configuration file.
        /// </summary>
        public HanditinEntities() : base("name=HanditinEntities", "HanditinEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HanditinEntities object.
        /// </summary>
        public HanditinEntities(string connectionString) : base(connectionString, "HanditinEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HanditinEntities object.
        /// </summary>
        public HanditinEntities(EntityConnection connection) : base(connection, "HanditinEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Class> Classes
        {
            get
            {
                if ((_Classes == null))
                {
                    _Classes = base.CreateObjectSet<Class>("Classes");
                }
                return _Classes;
            }
        }
        private ObjectSet<Class> _Classes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Group> Groups
        {
            get
            {
                if ((_Groups == null))
                {
                    _Groups = base.CreateObjectSet<Group>("Groups");
                }
                return _Groups;
            }
        }
        private ObjectSet<Group> _Groups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Project> Projects
        {
            get
            {
                if ((_Projects == null))
                {
                    _Projects = base.CreateObjectSet<Project>("Projects");
                }
                return _Projects;
            }
        }
        private ObjectSet<Project> _Projects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Score> Scores
        {
            get
            {
                if ((_Scores == null))
                {
                    _Scores = base.CreateObjectSet<Score>("Scores");
                }
                return _Scores;
            }
        }
        private ObjectSet<Score> _Scores;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Student> Students
        {
            get
            {
                if ((_Students == null))
                {
                    _Students = base.CreateObjectSet<Student>("Students");
                }
                return _Students;
            }
        }
        private ObjectSet<Student> _Students;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Submission> Submissions
        {
            get
            {
                if ((_Submissions == null))
                {
                    _Submissions = base.CreateObjectSet<Submission>("Submissions");
                }
                return _Submissions;
            }
        }
        private ObjectSet<Submission> _Submissions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Teacher> Teachers
        {
            get
            {
                if ((_Teachers == null))
                {
                    _Teachers = base.CreateObjectSet<Teacher>("Teachers");
                }
                return _Teachers;
            }
        }
        private ObjectSet<Teacher> _Teachers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Work> Works
        {
            get
            {
                if ((_Works == null))
                {
                    _Works = base.CreateObjectSet<Work>("Works");
                }
                return _Works;
            }
        }
        private ObjectSet<Work> _Works;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Classes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClasses(Class @class)
        {
            base.AddObject("Classes", @class);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Groups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGroups(Group group)
        {
            base.AddObject("Groups", group);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Projects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjects(Project project)
        {
            base.AddObject("Projects", project);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Scores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToScores(Score score)
        {
            base.AddObject("Scores", score);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Submissions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubmissions(Submission submission)
        {
            base.AddObject("Submissions", submission);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Teachers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTeachers(Teacher teacher)
        {
            base.AddObject("Teachers", teacher);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Works EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorks(Work work)
        {
            base.AddObject("Works", work);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HanditinModel", Name="Class")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Class : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Class object.
        /// </summary>
        /// <param name="cid">Initial value of the cid property.</param>
        public static Class CreateClass(global::System.Int32 cid)
        {
            Class @class = new Class();
            @class.cid = cid;
            return @class;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cid
        {
            get
            {
                return _cid;
            }
            set
            {
                if (_cid != value)
                {
                    OncidChanging(value);
                    ReportPropertyChanging("cid");
                    _cid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cid");
                    OncidChanged();
                }
            }
        }
        private global::System.Int32 _cid;
        partial void OncidChanging(global::System.Int32 value);
        partial void OncidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String class_name
        {
            get
            {
                return _class_name;
            }
            set
            {
                Onclass_nameChanging(value);
                ReportPropertyChanging("class_name");
                _class_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("class_name");
                Onclass_nameChanged();
            }
        }
        private global::System.String _class_name;
        partial void Onclass_nameChanging(global::System.String value);
        partial void Onclass_nameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_Student_Class", "Student")]
        public EntityCollection<Student> Students
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("HanditinModel.FK_Student_Class", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("HanditinModel.FK_Student_Class", "Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HanditinModel", Name="Group")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Group : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Group object.
        /// </summary>
        /// <param name="gid">Initial value of the gid property.</param>
        /// <param name="leader_sid">Initial value of the leader_sid property.</param>
        /// <param name="creator_sid">Initial value of the creator_sid property.</param>
        /// <param name="gname">Initial value of the gname property.</param>
        /// <param name="create_time">Initial value of the create_time property.</param>
        public static Group CreateGroup(global::System.Int32 gid, global::System.Int32 leader_sid, global::System.Int32 creator_sid, global::System.String gname, global::System.Byte[] create_time)
        {
            Group group = new Group();
            group.gid = gid;
            group.leader_sid = leader_sid;
            group.creator_sid = creator_sid;
            group.gname = gname;
            group.create_time = create_time;
            return group;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 gid
        {
            get
            {
                return _gid;
            }
            set
            {
                if (_gid != value)
                {
                    OngidChanging(value);
                    ReportPropertyChanging("gid");
                    _gid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("gid");
                    OngidChanged();
                }
            }
        }
        private global::System.Int32 _gid;
        partial void OngidChanging(global::System.Int32 value);
        partial void OngidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 leader_sid
        {
            get
            {
                return _leader_sid;
            }
            set
            {
                Onleader_sidChanging(value);
                ReportPropertyChanging("leader_sid");
                _leader_sid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("leader_sid");
                Onleader_sidChanged();
            }
        }
        private global::System.Int32 _leader_sid;
        partial void Onleader_sidChanging(global::System.Int32 value);
        partial void Onleader_sidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 creator_sid
        {
            get
            {
                return _creator_sid;
            }
            set
            {
                Oncreator_sidChanging(value);
                ReportPropertyChanging("creator_sid");
                _creator_sid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("creator_sid");
                Oncreator_sidChanged();
            }
        }
        private global::System.Int32 _creator_sid;
        partial void Oncreator_sidChanging(global::System.Int32 value);
        partial void Oncreator_sidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gname
        {
            get
            {
                return _gname;
            }
            set
            {
                OngnameChanging(value);
                ReportPropertyChanging("gname");
                _gname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("gname");
                OngnameChanged();
            }
        }
        private global::System.String _gname;
        partial void OngnameChanging(global::System.String value);
        partial void OngnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] create_time
        {
            get
            {
                return StructuralObject.GetValidValue(_create_time);
            }
            set
            {
                Oncreate_timeChanging(value);
                ReportPropertyChanging("create_time");
                _create_time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("create_time");
                Oncreate_timeChanged();
            }
        }
        private global::System.Byte[] _create_time;
        partial void Oncreate_timeChanging(global::System.Byte[] value);
        partial void Oncreate_timeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_group_leader_sid", "Student")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("HanditinModel.FK_group_leader_sid", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("HanditinModel.FK_group_leader_sid", "Student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("HanditinModel.FK_group_leader_sid", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("HanditinModel.FK_group_leader_sid", "Student", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_group_student", "Student")]
        public Student Student1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("HanditinModel.FK_group_student", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("HanditinModel.FK_group_student", "Student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> Student1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("HanditinModel.FK_group_student", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("HanditinModel.FK_group_student", "Student", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_submission_group", "Submission")]
        public EntityCollection<Submission> Submissions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Submission>("HanditinModel.FK_submission_group", "Submission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Submission>("HanditinModel.FK_submission_group", "Submission", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "Enrol", "Student")]
        public EntityCollection<Student> Students
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Student>("HanditinModel.Enrol", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Student>("HanditinModel.Enrol", "Student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HanditinModel", Name="Project")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Project : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="pid">Initial value of the pid property.</param>
        /// <param name="pname">Initial value of the pname property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="link">Initial value of the link property.</param>
        /// <param name="create_time">Initial value of the create_time property.</param>
        /// <param name="tid">Initial value of the tid property.</param>
        public static Project CreateProject(global::System.Int32 pid, global::System.String pname, global::System.String description, global::System.String link, global::System.Byte[] create_time, global::System.Int32 tid)
        {
            Project project = new Project();
            project.pid = pid;
            project.pname = pname;
            project.description = description;
            project.link = link;
            project.create_time = create_time;
            project.tid = tid;
            return project;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pid
        {
            get
            {
                return _pid;
            }
            set
            {
                if (_pid != value)
                {
                    OnpidChanging(value);
                    ReportPropertyChanging("pid");
                    _pid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pid");
                    OnpidChanged();
                }
            }
        }
        private global::System.Int32 _pid;
        partial void OnpidChanging(global::System.Int32 value);
        partial void OnpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pname
        {
            get
            {
                return _pname;
            }
            set
            {
                OnpnameChanging(value);
                ReportPropertyChanging("pname");
                _pname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("pname");
                OnpnameChanged();
            }
        }
        private global::System.String _pname;
        partial void OnpnameChanging(global::System.String value);
        partial void OnpnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String link
        {
            get
            {
                return _link;
            }
            set
            {
                OnlinkChanging(value);
                ReportPropertyChanging("link");
                _link = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("link");
                OnlinkChanged();
            }
        }
        private global::System.String _link;
        partial void OnlinkChanging(global::System.String value);
        partial void OnlinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> due
        {
            get
            {
                return _due;
            }
            set
            {
                OndueChanging(value);
                ReportPropertyChanging("due");
                _due = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("due");
                OndueChanged();
            }
        }
        private Nullable<global::System.DateTime> _due;
        partial void OndueChanging(Nullable<global::System.DateTime> value);
        partial void OndueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] create_time
        {
            get
            {
                return StructuralObject.GetValidValue(_create_time);
            }
            set
            {
                Oncreate_timeChanging(value);
                ReportPropertyChanging("create_time");
                _create_time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("create_time");
                Oncreate_timeChanged();
            }
        }
        private global::System.Byte[] _create_time;
        partial void Oncreate_timeChanging(global::System.Byte[] value);
        partial void Oncreate_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tid
        {
            get
            {
                return _tid;
            }
            set
            {
                OntidChanging(value);
                ReportPropertyChanging("tid");
                _tid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tid");
                OntidChanged();
            }
        }
        private global::System.Int32 _tid;
        partial void OntidChanging(global::System.Int32 value);
        partial void OntidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_project_teacher", "Teacher")]
        public Teacher Teacher
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("HanditinModel.FK_project_teacher", "Teacher").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("HanditinModel.FK_project_teacher", "Teacher").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Teacher> TeacherReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("HanditinModel.FK_project_teacher", "Teacher");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Teacher>("HanditinModel.FK_project_teacher", "Teacher", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_submission_project", "Submission")]
        public EntityCollection<Submission> Submissions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Submission>("HanditinModel.FK_submission_project", "Submission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Submission>("HanditinModel.FK_submission_project", "Submission", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HanditinModel", Name="Score")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Score : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Score object.
        /// </summary>
        /// <param name="gradeid">Initial value of the gradeid property.</param>
        /// <param name="sub_id">Initial value of the sub_id property.</param>
        /// <param name="tid">Initial value of the tid property.</param>
        /// <param name="score1">Initial value of the score1 property.</param>
        /// <param name="time">Initial value of the time property.</param>
        public static Score CreateScore(global::System.Int32 gradeid, global::System.Int32 sub_id, global::System.Int32 tid, global::System.Double score1, global::System.Byte[] time)
        {
            Score score = new Score();
            score.gradeid = gradeid;
            score.sub_id = sub_id;
            score.tid = tid;
            score.score1 = score1;
            score.time = time;
            return score;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 gradeid
        {
            get
            {
                return _gradeid;
            }
            set
            {
                if (_gradeid != value)
                {
                    OngradeidChanging(value);
                    ReportPropertyChanging("gradeid");
                    _gradeid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("gradeid");
                    OngradeidChanged();
                }
            }
        }
        private global::System.Int32 _gradeid;
        partial void OngradeidChanging(global::System.Int32 value);
        partial void OngradeidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sub_id
        {
            get
            {
                return _sub_id;
            }
            set
            {
                Onsub_idChanging(value);
                ReportPropertyChanging("sub_id");
                _sub_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sub_id");
                Onsub_idChanged();
            }
        }
        private global::System.Int32 _sub_id;
        partial void Onsub_idChanging(global::System.Int32 value);
        partial void Onsub_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tid
        {
            get
            {
                return _tid;
            }
            set
            {
                OntidChanging(value);
                ReportPropertyChanging("tid");
                _tid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tid");
                OntidChanged();
            }
        }
        private global::System.Int32 _tid;
        partial void OntidChanging(global::System.Int32 value);
        partial void OntidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double score1
        {
            get
            {
                return _score1;
            }
            set
            {
                Onscore1Changing(value);
                ReportPropertyChanging("score1");
                _score1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("score1");
                Onscore1Changed();
            }
        }
        private global::System.Double _score1;
        partial void Onscore1Changing(global::System.Double value);
        partial void Onscore1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comment
        {
            get
            {
                return _comment;
            }
            set
            {
                OncommentChanging(value);
                ReportPropertyChanging("comment");
                _comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comment");
                OncommentChanged();
            }
        }
        private global::System.String _comment;
        partial void OncommentChanging(global::System.String value);
        partial void OncommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] time
        {
            get
            {
                return StructuralObject.GetValidValue(_time);
            }
            set
            {
                OntimeChanging(value);
                ReportPropertyChanging("time");
                _time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("time");
                OntimeChanged();
            }
        }
        private global::System.Byte[] _time;
        partial void OntimeChanging(global::System.Byte[] value);
        partial void OntimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_socre_submission", "Submission")]
        public Submission Submission
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Submission>("HanditinModel.FK_socre_submission", "Submission").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Submission>("HanditinModel.FK_socre_submission", "Submission").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Submission> SubmissionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Submission>("HanditinModel.FK_socre_submission", "Submission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Submission>("HanditinModel.FK_socre_submission", "Submission", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_socre_teacher", "Teacher")]
        public Teacher Teacher
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("HanditinModel.FK_socre_teacher", "Teacher").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("HanditinModel.FK_socre_teacher", "Teacher").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Teacher> TeacherReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("HanditinModel.FK_socre_teacher", "Teacher");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Teacher>("HanditinModel.FK_socre_teacher", "Teacher", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HanditinModel", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="sid">Initial value of the sid property.</param>
        /// <param name="major">Initial value of the major property.</param>
        /// <param name="class">Initial value of the class property.</param>
        public static Student CreateStudent(global::System.Int32 sid, global::System.Int32 major, global::System.Int32 @class)
        {
            Student student = new Student();
            student.sid = sid;
            student.major = major;
            student.@class = @class;
            return student;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sid
        {
            get
            {
                return _sid;
            }
            set
            {
                if (_sid != value)
                {
                    OnsidChanging(value);
                    ReportPropertyChanging("sid");
                    _sid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sid");
                    OnsidChanged();
                }
            }
        }
        private global::System.Int32 _sid;
        partial void OnsidChanging(global::System.Int32 value);
        partial void OnsidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 major
        {
            get
            {
                return _major;
            }
            set
            {
                OnmajorChanging(value);
                ReportPropertyChanging("major");
                _major = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("major");
                OnmajorChanged();
            }
        }
        private global::System.Int32 _major;
        partial void OnmajorChanging(global::System.Int32 value);
        partial void OnmajorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 @class
        {
            get
            {
                return _class;
            }
            set
            {
                OnclassChanging(value);
                ReportPropertyChanging("class");
                _class = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("class");
                OnclassChanged();
            }
        }
        private global::System.Int32 _class;
        partial void OnclassChanging(global::System.Int32 value);
        partial void OnclassChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_Student_Class", "Class")]
        public Class Class1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Class>("HanditinModel.FK_Student_Class", "Class").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Class>("HanditinModel.FK_Student_Class", "Class").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Class> Class1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Class>("HanditinModel.FK_Student_Class", "Class");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Class>("HanditinModel.FK_Student_Class", "Class", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_group_leader_sid", "Group")]
        public EntityCollection<Group> Groups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Group>("HanditinModel.FK_group_leader_sid", "Group");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Group>("HanditinModel.FK_group_leader_sid", "Group", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_group_student", "Group")]
        public EntityCollection<Group> Groups1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Group>("HanditinModel.FK_group_student", "Group");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Group>("HanditinModel.FK_group_student", "Group", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_student_user", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("HanditinModel.FK_student_user", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("HanditinModel.FK_student_user", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("HanditinModel.FK_student_user", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("HanditinModel.FK_student_user", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "Enrol", "Group")]
        public EntityCollection<Group> Groups2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Group>("HanditinModel.Enrol", "Group");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Group>("HanditinModel.Enrol", "Group", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HanditinModel", Name="Submission")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Submission : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Submission object.
        /// </summary>
        /// <param name="sub_id">Initial value of the sub_id property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="gid">Initial value of the gid property.</param>
        /// <param name="pid">Initial value of the pid property.</param>
        /// <param name="sub_time">Initial value of the sub_time property.</param>
        public static Submission CreateSubmission(global::System.Int32 sub_id, global::System.String title, global::System.Int32 gid, global::System.Int32 pid, global::System.DateTime sub_time)
        {
            Submission submission = new Submission();
            submission.sub_id = sub_id;
            submission.title = title;
            submission.gid = gid;
            submission.pid = pid;
            submission.sub_time = sub_time;
            return submission;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sub_id
        {
            get
            {
                return _sub_id;
            }
            set
            {
                if (_sub_id != value)
                {
                    Onsub_idChanging(value);
                    ReportPropertyChanging("sub_id");
                    _sub_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sub_id");
                    Onsub_idChanged();
                }
            }
        }
        private global::System.Int32 _sub_id;
        partial void Onsub_idChanging(global::System.Int32 value);
        partial void Onsub_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 gid
        {
            get
            {
                return _gid;
            }
            set
            {
                OngidChanging(value);
                ReportPropertyChanging("gid");
                _gid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gid");
                OngidChanged();
            }
        }
        private global::System.Int32 _gid;
        partial void OngidChanging(global::System.Int32 value);
        partial void OngidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pid
        {
            get
            {
                return _pid;
            }
            set
            {
                OnpidChanging(value);
                ReportPropertyChanging("pid");
                _pid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pid");
                OnpidChanged();
            }
        }
        private global::System.Int32 _pid;
        partial void OnpidChanging(global::System.Int32 value);
        partial void OnpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime sub_time
        {
            get
            {
                return _sub_time;
            }
            set
            {
                Onsub_timeChanging(value);
                ReportPropertyChanging("sub_time");
                _sub_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sub_time");
                Onsub_timeChanged();
            }
        }
        private global::System.DateTime _sub_time;
        partial void Onsub_timeChanging(global::System.DateTime value);
        partial void Onsub_timeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_submission_group", "Group")]
        public Group Group
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Group>("HanditinModel.FK_submission_group", "Group").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Group>("HanditinModel.FK_submission_group", "Group").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Group> GroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Group>("HanditinModel.FK_submission_group", "Group");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Group>("HanditinModel.FK_submission_group", "Group", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_submission_project", "Project")]
        public Project Project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("HanditinModel.FK_submission_project", "Project").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("HanditinModel.FK_submission_project", "Project").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Project> ProjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Project>("HanditinModel.FK_submission_project", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Project>("HanditinModel.FK_submission_project", "Project", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_socre_submission", "Score")]
        public EntityCollection<Score> Scores
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Score>("HanditinModel.FK_socre_submission", "Score");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Score>("HanditinModel.FK_socre_submission", "Score", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "SubmittedWork", "Work")]
        public EntityCollection<Work> Works
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Work>("HanditinModel.SubmittedWork", "Work");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Work>("HanditinModel.SubmittedWork", "Work", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HanditinModel", Name="Teacher")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Teacher : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Teacher object.
        /// </summary>
        /// <param name="tid">Initial value of the tid property.</param>
        public static Teacher CreateTeacher(global::System.Int32 tid)
        {
            Teacher teacher = new Teacher();
            teacher.tid = tid;
            return teacher;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tid
        {
            get
            {
                return _tid;
            }
            set
            {
                if (_tid != value)
                {
                    OntidChanging(value);
                    ReportPropertyChanging("tid");
                    _tid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("tid");
                    OntidChanged();
                }
            }
        }
        private global::System.Int32 _tid;
        partial void OntidChanging(global::System.Int32 value);
        partial void OntidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_project_teacher", "Project")]
        public EntityCollection<Project> Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("HanditinModel.FK_project_teacher", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("HanditinModel.FK_project_teacher", "Project", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_socre_teacher", "Score")]
        public EntityCollection<Score> Scores
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Score>("HanditinModel.FK_socre_teacher", "Score");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Score>("HanditinModel.FK_socre_teacher", "Score", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_teacher_user", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("HanditinModel.FK_teacher_user", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("HanditinModel.FK_teacher_user", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("HanditinModel.FK_teacher_user", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("HanditinModel.FK_teacher_user", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HanditinModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="uid">Initial value of the uid property.</param>
        /// <param name="uname">Initial value of the uname property.</param>
        /// <param name="upass">Initial value of the upass property.</param>
        /// <param name="email">Initial value of the email property.</param>
        public static User CreateUser(global::System.Int32 uid, global::System.String uname, global::System.String upass, global::System.Byte[] email)
        {
            User user = new User();
            user.uid = uid;
            user.uname = uname;
            user.upass = upass;
            user.email = email;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 uid
        {
            get
            {
                return _uid;
            }
            set
            {
                if (_uid != value)
                {
                    OnuidChanging(value);
                    ReportPropertyChanging("uid");
                    _uid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uid");
                    OnuidChanged();
                }
            }
        }
        private global::System.Int32 _uid;
        partial void OnuidChanging(global::System.Int32 value);
        partial void OnuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String uname
        {
            get
            {
                return _uname;
            }
            set
            {
                OnunameChanging(value);
                ReportPropertyChanging("uname");
                _uname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("uname");
                OnunameChanged();
            }
        }
        private global::System.String _uname;
        partial void OnunameChanging(global::System.String value);
        partial void OnunameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String upass
        {
            get
            {
                return _upass;
            }
            set
            {
                OnupassChanging(value);
                ReportPropertyChanging("upass");
                _upass = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("upass");
                OnupassChanged();
            }
        }
        private global::System.String _upass;
        partial void OnupassChanging(global::System.String value);
        partial void OnupassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] email
        {
            get
            {
                return StructuralObject.GetValidValue(_email);
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.Byte[] _email;
        partial void OnemailChanging(global::System.Byte[] value);
        partial void OnemailChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_student_user", "Student")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("HanditinModel.FK_student_user", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("HanditinModel.FK_student_user", "Student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("HanditinModel.FK_student_user", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("HanditinModel.FK_student_user", "Student", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "FK_teacher_user", "Teacher")]
        public Teacher Teacher
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("HanditinModel.FK_teacher_user", "Teacher").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("HanditinModel.FK_teacher_user", "Teacher").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Teacher> TeacherReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("HanditinModel.FK_teacher_user", "Teacher");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Teacher>("HanditinModel.FK_teacher_user", "Teacher", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HanditinModel", Name="Work")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Work : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Work object.
        /// </summary>
        /// <param name="wid">Initial value of the wid property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="hyperlink">Initial value of the hyperlink property.</param>
        public static Work CreateWork(global::System.Int32 wid, global::System.String title, global::System.String hyperlink)
        {
            Work work = new Work();
            work.wid = wid;
            work.title = title;
            work.hyperlink = hyperlink;
            return work;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 wid
        {
            get
            {
                return _wid;
            }
            set
            {
                if (_wid != value)
                {
                    OnwidChanging(value);
                    ReportPropertyChanging("wid");
                    _wid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("wid");
                    OnwidChanged();
                }
            }
        }
        private global::System.Int32 _wid;
        partial void OnwidChanging(global::System.Int32 value);
        partial void OnwidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String hyperlink
        {
            get
            {
                return _hyperlink;
            }
            set
            {
                OnhyperlinkChanging(value);
                ReportPropertyChanging("hyperlink");
                _hyperlink = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("hyperlink");
                OnhyperlinkChanged();
            }
        }
        private global::System.String _hyperlink;
        partial void OnhyperlinkChanging(global::System.String value);
        partial void OnhyperlinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private Nullable<global::System.Int32> _type;
        partial void OntypeChanging(Nullable<global::System.Int32> value);
        partial void OntypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HanditinModel", "SubmittedWork", "Submission")]
        public EntityCollection<Submission> Submissions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Submission>("HanditinModel.SubmittedWork", "Submission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Submission>("HanditinModel.SubmittedWork", "Submission", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
